config/routes.rb
Rails.application.routes.draw do
  resources :appearances, only: [:index,:show,:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :guests, only: [:index,:show]
  resources :episodes, only: [:index, :show]
end

app/models/appearance.rb
class Appearance < ApplicationRecord
    belongs_to :guest
    belongs_to :episode
    validates :rating, numericality: {less_than: 6}
    validates :rating, numericality: {greater_than: 0}
    validates :guest_id, uniqueness: {scope: :episode,
        message: "only one per episode"}


        
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
    has_many :appearances
    has_many :guests, through: :appearances

    def avg_rating
        rating_count = self.appearances.length
        rating_total = self.appearances.map{|a| a.rating}.sum.to_f
        rating_total/rating_count
    end
end

app/models/guest.rb
class Guest < ApplicationRecord
    has_many :appearances
    has_many :episodes, through: :appearances

    def sorted_appearances
        self.appearances.sort_by{|a| -a.rating}
    end
end

app/controllers/appearances_controller.rb
class AppearancesController < ApplicationController
    
    def show
        @appearance = Appearance.find(params[:id])
    end

    def new
        @appearance = Appearance.new
    end

    def create
        @appearance = Appearance.create(appearance_params)
        if @appearance.valid?
            redirect_to appearance_path(@appearance.id)
        else
            render "new"
        end
        
    end


    private

    def appearance_params
        params.require(:appearance).permit(:rating,:guest_id,:episode_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def show
    @episode = Episode.find(params[:id])
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end
end

app/helpers/appearances_helper.rb
module AppearancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/appearances/_form.html.erb
<% if !@appearance.valid? %>
    <ul>
        <% @appearance.errors.full_messages.each do |err| %>
            <%=err%>
        <% end %>
    </ul>
<% end %>

    <%= form_for @appearance do |f| %>
        <%= f.label :guest_id, "Select a Guest:" %>
        <%= f.collection_select :guest_id, Guest.all, :id, :name %><br>

        <%= f.label :episode_id, "Select an Episode:" %>
        <%= f.collection_select :episode_id, Episode.all, :id, :number %><br>
        
        <%= f.label :rating, "Rate it:" %>
        <%= f.text_field :rating %><br>
        <% if false %>
        <%= select_tag :rating, options_for_select(1..5) %>
        
        <% end %>
        <%= f.submit %>
    <% end %>

app/views/appearances/new.html.erb
<h1>Create a new Appearance here</h2>
<%= render  "form", appearance:@appearance %>

app/views/appearances/show.html.erb
<h1>This is an appeareance show page</h1>

<%="This appearance was rated #{@appearance.rating}" %>

app/views/episodes/index.html.erb
<h1>All Episodes</h1>

<ul>
  <% @episodes.each do |episode| %>
    <li><%= "Episode #{episode.number} - #{episode.date.strftime("%B %d, %Y")}"%></li>
  <% end %>
</ul>

app/views/episodes/show.html.erb
<h1>Episode Show page</h2>

<%= @episode.date%><br>
<%= @episode.avg_rating%><br>

<% @episode.guests.each do |guest| %>
    <%= link_to  guest.name, guest_path(guest.id) %>
<% end %>

app/views/guests/index.html.erb
<h1>All The Guests</h1>

<ul>
  <% @guests.each do |guest| %>
   
    <li><%= link_to  guest.name, guest_path(guest.id) %> </li>
  <% end %>
</ul>

app/views/guests/show.html.erb
<h2>Guest Show</h2>

<%=@guest.name%>
<p>List of episodes</p>
<ul>
    <% @guest.sorted_appearances.each do |app|%>
        <li>   
            <%="rating: #{app.rating}" %><br>
            <%= "episode date: #{app.episode.date}" %>
        </li>
    <% end %>
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImmersiveRailsAssessment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>